# See http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# Versions of PHP to test against
php:
  - 5.5
  - 5.4

# Setup before the tests
# Install nginx and turn on php
before_script:
  - sudo apt-get -qq install nginx
  - php-cgi -b 127.0.0.1:9000 &
  - sudo nginx -c app/tests/nginx.conf -p "$PWD/"
  - composer self-update -n
  - composer install --dev -n --prefer-source

# Run tests through Codeception
script: php-cgi codecept.phar run -n -c "codeception.travis.yml"
