# See http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# Versions of PHP to test against
php:
  - 5.5
  - 5.4
  - 5.3

# Setup before the tests
before_script:
  - php hostname.php
  - composer self-update
  - composer install --dev --no-interaction --prefer-source

# Run unit and functional tests.
# Not sure how to setup for running acceptance tests
script: vendor/bin/codecept run -s acceptance
