title: DEPRECATED—Enhanced Laravel Project Seeder
description: Formerly the fastest way to start a new Laravel project
google_analytics: UA-11203531-11
show_downloads: false
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
