#!/usr/bin/env php
<?php

require __DIR__.'/bootstrap/autoload.php';
$app = require_once __DIR__.'/bootstrap/start.php';
$app->setRequestForConsoleEnvironment();
$artisan = Illuminate\Console\Application::start($app);
$status = $artisan->run();
$app->shutdown();
exit($status);
